= SSL/TLS

SL (Secure Sockets Layer) and its successor, TLS (Transport Layer Security), are protocols for establishing authenticated and encrypted links between networked computers.
Although the SSL protocol was deprecated with the release of TLS 1.0 in 1999, it is still common to refer to these related technologies as “SSL” or “SSL/TLS”.
The most current version is TLS 1.3, defined in RFC 8446 (August 2018).

== One way authentication:

=== Case 1:

* Client (HTTP)
* Server (HTTPS)
** client-auth: none|want

Client: HTTP

.application.yml:
----
NO SSL CONFIGURATION
----

.VM options:
* Client need truststore to hold server certificate(s), used to validate server in SSL/TLS handshake.
* Note: Adding truststore information in the server.ssl is not effective in this case.
----
-Djavax.net.ssl.trustStore=<path to truststore>
-Djavax.net.ssl.trustStorePassword=<truststore password>
----


Server: HTTPS

.application.yml:
* Server need keystore to hold server certificate to share with the client for SSL/TLS handshake.
----
ssl:
    enabled: true
    client-auth: none|want
    key-store: C:\Users\muku3\projects\mutual-tls\self-signed-certificates\client\keystore.jks
    key-store-password: svn4ever
----

.VM options:
----
NO VM OPTION REQUIRED
----

=== Case 2:

=== Case 3:

=== Case 4:

=== Case 5: