#
# Server
#
server:
  port: 8000
  ssl:
    enabled: true
    client-auth: want # want|none
    key-store: C:\Users\muku3\projects\mutual-tls\self-signed-certificates\client\keystore.jks
    key-store-password: svn4ever


