#
#     CLIENT
#
server:
  port: 9000
  ssl:
    enabled: true
    client-auth: want
    # Keystore
    key-store: C:\\Users\\muku3\\projects\\mutual-tls\\dev-certificates\\client\\keystore.jks
    key-store-password: svn4ever
    key-password: svn4ever
    trust-store=classpath: C:\\Users\\muku3\\projects\\mutual-tls\\dev-certificates\\client\\truststore.jks
    trust-store-password: svn4ever